# Generated by Django 5.2.6 on 2025-10-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_delete_reportattachment'),
        ('voice_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicelog',
            options={},
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='intent',
            field=models.CharField(default='note', max_length=50, verbose_name='インテント'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='text',
            field=models.TextField(verbose_name='テキスト'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='ts',
            field=models.CharField(default='', max_length=100, verbose_name='タイムスタンプ文字列'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='when',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
    ]
