# Generated by Django 5.2.5 on 2025-09-03 03:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='営業担当')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=200, verbose_name='案件名')),
                ('amount', models.IntegerField(default=0, verbose_name='金額')),
                ('status', models.CharField(choices=[('discussion', '商談中'), ('proposal', '提案済'), ('won', '受注'), ('lost', '失注'), ('working', '作業中'), ('completed', '完了')], default='discussion', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.customer', verbose_name='顧客')),
                ('person_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
        ),
        migrations.CreateModel(
            name='DealStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='ステータス')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='変更日時')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reports.deal', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件ステータス履歴',
                'verbose_name_plural': '案件ステータス履歴',
                'ordering': ['deal', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='件名')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.customer', verbose_name='顧客')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='項目')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_items', to='reports.deal', verbose_name='関連案件')),
            ],
            options={
                'verbose_name': '必要物品',
                'verbose_name_plural': '必要物品',
                'ordering': ['is_done', 'deal__deal_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TroubleshootingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('location', models.CharField(max_length=200, verbose_name='場所・機器')),
                ('symptom', models.TextField(verbose_name='症状・問題')),
                ('solution', models.TextField(verbose_name='対応・解決策')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='検索キーワード')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'verbose_name': 'トラブルシュート報告書',
                'verbose_name_plural': 'トラブルシュート報告書',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='作業日')),
                ('work_hours', models.DurationField(default=datetime.timedelta, verbose_name='作業時間')),
                ('progress_status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '作業中'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='進捗状況')),
                ('repair_needed', models.TextField(blank=True, null=True, verbose_name='修理・対応が必要な事項')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='添付ファイル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作業者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.customer', verbose_name='顧客')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.deal', verbose_name='案件')),
            ],
        ),
    ]
