# Generated by Django 5.2.5 on 2025-09-08 03:22

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='営業担当')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=200, verbose_name='案件名')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.customer', verbose_name='顧客')),
            ],
        ),
        migrations.CreateModel(
            name='DealStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='ステータス')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='変更日時')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reports.deal', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件ステータス履歴',
                'verbose_name_plural': '案件ステータス履歴',
                'ordering': ['deal', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='場所・顧客名')),
                ('deal_name', models.CharField(blank=True, max_length=200, verbose_name='案件名')),
                ('work_date', models.DateField(verbose_name='作業日')),
                ('progress_status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '作業中'), ('completed', '完了')], default='in_progress', max_length=20, verbose_name='進捗')),
                ('work_hours', models.DurationField(default=datetime.timedelta, verbose_name='作業時間')),
                ('work_details', models.TextField(verbose_name='【最重要】今日の作業内容')),
                ('remarks', models.TextField(blank=True, verbose_name='所感・連絡事項など')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='添付ファイル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='RequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='項目')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_items', to='reports.deal', verbose_name='関連案件')),
            ],
            options={
                'verbose_name': '必要物品',
                'verbose_name_plural': '必要物品',
                'ordering': ['is_done', 'deal__deal_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TroubleshootingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='例：揚水ポンプの送水不良', max_length=200, verbose_name='タイトル')),
                ('location', models.CharField(help_text='例：機械室 揚水ポンプ Model-102', max_length=200, verbose_name='場所・機器')),
                ('work_details', models.TextField(default='', verbose_name='今日の作業内容')),
                ('symptom', models.TextField(help_text='例：水を吸い上げず送水できない。', verbose_name='症状・問題')),
                ('solution', models.TextField(help_text='例：バルブを取り外し清掃、パッキン交換。', verbose_name='対応・解決策')),
                ('keywords', models.CharField(blank=True, help_text='例：ポンプ, バルブ, 異音', max_length=200, verbose_name='検索キーワード')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'verbose_name': 'トラブルシュート報告書',
                'verbose_name_plural': 'トラブルシュート報告書',
                'ordering': ['-updated_at'],
            },
        ),
    ]
