# Generated by Django 4.2.24 on 2025-09-29 07:05

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicelog',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.voicelog_upload_to, verbose_name='音声ファイル'),
        ),
        migrations.AddField(
            model_name='voicelog',
            name='duration_sec',
            field=models.FloatField(default=0.0, verbose_name='長さ(秒)'),
        ),
        migrations.AddField(
            model_name='voicelog',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME'),
        ),
    ]
