# Generated by Django 4.2.16 on 2025-10-07 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_voicelog_audio_file_voicelog_duration_sec_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voicelog',
            name='reports_voi_intent_8a34ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='voicelog',
            name='reports_voi_created_f2e5ac_idx',
        ),
        migrations.RemoveField(
            model_name='requireditem',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='voicelog',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='voicelog',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='voicelog',
            name='duration_sec',
        ),
        migrations.RemoveField(
            model_name='voicelog',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='voicelog',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='voicelog',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='voicelog',
            name='when',
        ),
        migrations.AddField(
            model_name='requireditem',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
        migrations.AddField(
            model_name='requireditem',
            name='required_items_list',
            field=models.TextField(blank=True, help_text='一行に一つずつ入力してください。', verbose_name='必要物リスト'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='ts',
            field=models.CharField(blank=True, max_length=50, verbose_name='送信時刻(ISO文字列)'),
        ),
    ]
