# Generated by Django 4.2.16 on 2025-10-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_voicelog_reports_voi_intent_8a34ac_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportAttachment',
        ),
    ]
