# Generated by Django 5.2.6 on 2025-10-11 04:07

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_delete_reportattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_person',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='close_date',
            new_name='expected_order_date',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='deal_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='remarks',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='content',
            new_name='work_content',
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='requireditem',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.deal', verbose_name='関連案件'),
        ),
        migrations.AddField(
            model_name='voicelog',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額(円)'),
        ),
        migrations.AddField(
            model_name='voicelog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.customer', verbose_name='顧客'),
        ),
        migrations.AddField(
            model_name='voicelog',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='voicelog',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
        migrations.AddField(
            model_name='voicelog',
            name='when',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('proposal', '提案中'), ('in_progress', '進行中'), ('won', '受注'), ('lost', '失注')], default='in_progress', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='requireditem',
            name='required_items_list',
            field=models.TextField(blank=True, verbose_name='必要物品リスト'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='ts',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='送信時刻(ISO文字列)'),
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reports.models.attachment_upload_to, verbose_name='ファイル')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report', verbose_name='日報')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
