# Generated by Django 5.2.6 on 2025-10-12 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_rename_contact_person_customer_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_name',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='expected_order_date',
            new_name='close_date',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='name',
            new_name='deal_name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='work_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='note',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.RemoveField(
            model_name='requireditem',
            name='required_items_list',
        ),
        migrations.AddField(
            model_name='voicelog',
            name='duration_sec',
            field=models.FloatField(default=0.0, verbose_name='長さ(秒)'),
        ),
        migrations.AddField(
            model_name='voicelog',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('proposal', '提案中'), ('in_progress', '進行中'), ('won', '受注'), ('lost', '失注')], default='proposal', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='requireditem',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='customer',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='ts',
            field=models.CharField(max_length=50, verbose_name='送信時刻(ISO文字列)'),
        ),
        migrations.AlterField(
            model_name='voicelog',
            name='when',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='予定時刻(ISO文字列)'),
        ),
        migrations.AddIndex(
            model_name='voicelog',
            index=models.Index(fields=['intent'], name='reports_voi_intent_8a34ac_idx'),
        ),
        migrations.AddIndex(
            model_name='voicelog',
            index=models.Index(fields=['created_at'], name='reports_voi_created_f2e5ac_idx'),
        ),
    ]
