# Generated by Django 5.2.6 on 2025-10-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_contact_name_customer_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireditem',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
    ]
