# Generated by Django 5.2.6 on 2025-10-13 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_requireditem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireditem',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='reports.report', verbose_name='関連日報'),
        ),
    ]
