# Generated by Django 5.2.6 on 2025-10-13 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_requireditem_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireditem',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細メモ'),
        ),
        migrations.AlterField(
            model_name='requireditem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        migrations.CreateModel(
            name='RequiredMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物品名')),
                ('quantity', models.CharField(blank=True, default='1', max_length=100, verbose_name='数量')),
                ('status', models.CharField(choices=[('needed', '必要'), ('procured', '調達済')], default='needed', max_length=20, verbose_name='状態')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='追加者')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_materials', to='reports.report', verbose_name='関連日報')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
