# Generated by Django 5.2.5 on 2025-09-11 12:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='会社名')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=200, verbose_name='案件名')),
                ('status', models.CharField(choices=[('proposal', '提案中'), ('in_progress', '進行中'), ('won', '受注'), ('lost', '失注')], default='proposal', max_length=20, verbose_name='ステータス')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='金額')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='受注予定日')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='reports.customer', verbose_name='顧客')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='背景画像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='場所')),
                ('progress', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '作業中'), ('completed', '完了')], default='in_progress', max_length=20, verbose_name='進捗')),
                ('work_hours', models.DurationField(default=datetime.timedelta, verbose_name='作業時間')),
                ('content', models.TextField(verbose_name='作業内容')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='項目')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.deal', verbose_name='関連案件')),
            ],
        ),
        migrations.CreateModel(
            name='Troubleshooting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('location', models.CharField(max_length=200, verbose_name='場所・機器')),
                ('symptom', models.TextField(verbose_name='症状・問題')),
                ('solution', models.TextField(verbose_name='対応・解決策')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='キーワード')),
                ('occurred_at', models.DateField(default=django.utils.timezone.now, verbose_name='発生日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
        ),
    ]
