# Generated by Django 4.2.24 on 2025-09-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='本文')),
                ('intent', models.CharField(default='note', max_length=50, verbose_name='意図')),
                ('ts', models.CharField(max_length=50, verbose_name='送信時刻(ISO文字列)')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='金額(円)')),
                ('customer', models.CharField(blank=True, max_length=120, null=True, verbose_name='顧客')),
                ('when', models.CharField(blank=True, max_length=50, null=True, verbose_name='予定時刻(ISO文字列)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='受信日時')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['intent'], name='reports_voi_intent_8a34ac_idx'), models.Index(fields=['created_at'], name='reports_voi_created_f2e5ac_idx')],
            },
        ),
    ]
